version: '3.8'

services:
  jargonjester-db:
    image: mysql:8.0
    container_name: jargonjester-db
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - jargonjester-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
      interval: 3s
  jargonjester-discord:
    container_name: jargonjester-discord
    build: 
      context: ./
      dockerfile: ./cmd/discord/Dockerfile
    depends_on:
      jargonjester-db:
        condition: service_healthy
    ports:
      - 8888:8888
  jargonjester-migration:
    container_name: jargonjester-migration
    build: 
      context: ./
      dockerfile: ./cmd/migration/Dockerfile
    depends_on:
      jargonjester-db:
        condition: service_healthy
volumes:
  jargonjester-db:
